implements chart
EXPRESSIM/GreenWay pull request #2
Opened 2017-04-18 05:37 UTC by planr0423

##图表功能前端页面
-使用了Echarts插件
-按时段为Chart1  按日为Chart2 按月为Chart3

2017-04-18 05:39 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/includes/app/data/admin-menu.js
> +        {
注意缩进

2017-04-18 05:42 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/includes/app/css/Check.css
> +div {
定义所有div的样式比较有风险，用.className来做selector

2017-04-18 05:42 UTC, planr0423 commented on Web/ExpressIM/WebContent/includes/app/data/admin-menu.js
> +        {
好的，我会注意

2017-04-18 05:42 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/includes/app/css/Check.css
> +	float: left;
缩进

2017-04-18 05:44 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/includes/app/util/Echarts/Chart1.js
> +$(function () {
1. Chart1,2,3这样的命名不规范，无论类的命名还是变量的命名，都应该有明确的含义,比如:MonthSummaryChartView, DaySummaryChartView, YearSummaryChartView

2017-04-18 05:46 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/includes/app/util/Echarts/Chart1.js
> +    var myChart = echarts.init(document.getElementById('chart'));
myChart 命名不规范

2017-04-18 05:47 UTC, HYKINGDOM commented on Web/ExpressIM/WebContent/includes/app/util/Echarts/Chart1.js
> +$(function () {
chart1.js，里面的ajax ，有一个URL ，应该怎么写。

2017-04-18 05:50 UTC, planr0423 commented on Web/ExpressIM/WebContent/includes/app/util/Echarts/Chart1.js
> +$(function () {
我尝试一下。

2017-04-18 05:51 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/includes/app/util/Echarts/Chart1.js
> +$(function () {
首先ajax的逻辑不应该放在chart里面，chart考虑的东西很简单，你给我什么数据我渲染什么图标，至于怎么拿数据，从哪拿，chart这个组件不应该需要知道

2017-04-18 05:54 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/includes/app/css/Check.css
> +@CHARSET "UTF-8";
Check这个文件命名也不太合适，并不能很好的理解代表的含义

2017-04-20 04:10 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/model/ChartModel.js
> +            var MyChart = echarts.init(document.getElementById('chart'));
init的参数应该是this._container, 由外面传入的一个对象

2017-04-20 04:12 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/model/ChartModel.js
> +                title:{
需要对options里面的字段进行一个分类，哪些是必要的，哪些不是必要的。哪些需要从外面传入，哪些需要内部生成
比如 data x, y，这个应该是由view或者model生成出来的. 有些需要从外面传，比如你图表的title

2017-04-20 04:21 UTC, codedoggylicheng requested changes

2017-04-20 04:21 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/model/ChartModel.js
> +$(document).ready(function () {
这段js不应该放在ChartModel.js里面，你这端代码里有view的定义，model的定义，还有view和model的使用
 - 你可以建立一个Chart.js 放在includes/util下面, Chart.js里面放现在的ChartView类的定义和未来子类的定义
 - 新建一个SummaryChartViewModel.js放在现有的model文件夹里 然后把ChartModel的定义放在这里面
 - 新建一个或者重命名你之前的rptCheck2.html -> rptSummaryChart.html, 然后把ChartView和ChartModel的使用放在这个文件的script段(document.ready....)
 - 删除无用文件

2017-04-20 08:09 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/reporting/rptSummaryChart.html
> +    $(document).ready(function () {
整个这段代码都没有用吧

2017-04-20 08:10 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/controller/CheckChart.js
> +// /**
注释删除掉

2017-04-20 09:44 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/reporting/rptSummaryChart.html
> +<div id="testModel"></div>
testModel没用了

2017-04-20 09:45 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/reporting/rptSummaryChart.html
> +        <div id ="left"></div>
left这个div是干嘛的

2017-04-20 09:45 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/reporting/rptSummaryChart.html
> +                <small></small>
small tag没用删掉

2017-04-20 09:45 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/reporting/rptSummaryChart.html
> +                <!--
多余的注释删掉

2017-04-20 09:46 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/reporting/rptSummaryChart.html
> +    <div id="footer"> <!-- 标题栏 -->
这部分应该不是footer, id="footer"不合适

2017-04-20 09:49 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/includes/app/util/Echarts/Chart.js
> +        var MyChart = echarts.init(this._container)
MyChart....is not good naming....

2017-04-20 09:50 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/includes/app/util/Echarts/Chart.js
> +        var options={
分析一下options里面哪些字段是必要的，哪些不是必要的。哪些可以抽出来

2017-04-24 08:09 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/controller/CheckChart.js
> +        this._summaryType.options("value").bind("focus", (function () {
```js
this._summaryType.options("value").bind("focus", (function () {
 +            this._setFieldValue(this.find("summaryType"), "");
 +        }).bind(this)).bind(this);
```
这段是干嘛的

2017-04-24 08:09 UTC, codedoggylicheng commented on Web/ExpressIM/WebContent/modules/controller/CheckChart.js
> +        this._summaryType.options("value").bind("focus", (function () {
另外确保这个summaryType有个默认值，比如按天

2017-04-24 08:42 UTC, codedoggylicheng approved these changes

2017-04-24 08:43 UTC, codedoggylicheng commented
LGTM :thumbsup:

2017-04-24 08:45 UTC, merged