chart implements
EXPRESSIM/GreenWay pull request #6
Opened 2017-04-27 01:43 UTC by HYKINGDOM

-数据层
-业务层

2017-04-27 01:50 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +		public void getPeriodSummaryMap(Date starDate, Date endDate, IHistoryRecordGate.PeriodSummaryType summaryType) {
代码没有格式化

2017-04-27 03:43 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +		ArrayList<Object> list = new ArrayList<Object>();
- 没必要new 一个ArrayList出来
- list的类型应该是List<Object>
```java
List<Object> list = ((IHistoryRecordGate) gate).getPeriodSummaryData(starDate, endDate, summaryType);
```
- map的类型是Map<String, Double>
- 变量命名要有意思list和map都没有明确的意思

2017-04-27 03:48 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +	    if(summaryType.equals(IHistoryRecordGate.PeriodSummaryType.BY_DAY)){
仔细想来我们是否真的需要一个if判断?第一列永远是amount那就可以
```java
Double amount = new Double(columns[0]);
String key = "";
for (int i=1;i<columns.length;i++) {
   key+=columns[i];
}
map.put(key, amount);
```

还有尽量用java的foreach
```java
for (Object [] columns : list) {
  ...
}
```

2017-04-27 04:35 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/dao/implementations/HistoryRecordGate.java
> +			List dateList = query.list();
直接return query.list()

2017-04-27 04:35 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/dao/implementations/HistoryRecordGate.java
> +					+ range + "");
最后的+""多余了

2017-04-27 04:36 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/dao/implementations/HistoryRecordGate.java
> +			}
注意缩进

2017-04-27 04:36 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/dao/abstracts/IHistoryRecordGate.java
> +		BY_MONTH, BY_YEAR, BY_DAY;
缩进

2017-04-27 04:36 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +		public void getPeriodSummaryMap(Date starDate, Date endDate, IHistoryRecordGate.PeriodSummaryType summaryType) {
缩进

2017-04-27 04:41 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +	    	System.out.print(map);
测试代码删除

2017-04-27 23:22 UTC, codedoggylicheng requested changes
大体没有问题了，把我上面说的几个问题修好

2017-04-27 23:22 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/actions/ChartAction.java
> +        bo.getPeriodSummaryMap(startDate,endDate,summaryType);
bo的返回值怎么发给前台的？

2017-04-27 23:22 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +        for (int i = 0; i <= summarylist.size(); i++) {
foreach

2017-04-27 23:22 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +        for (int i = 0; i <= summarylist.size(); i++) {
这块逻辑不太对，你debug一下看看你key是什么.然后再仔细看下我昨天给你的代码。PR之前自己要debug和测试一下

2017-04-27 23:22 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +        for (int i = 0; i <= summarylist.size(); i++) {
另外用stringbuilder

2017-04-27 23:22 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +        for (int i = 0; i <= summarylist.size(); i++) {
stringbuilder的速度要远高于stringbuffer 因为key是一个局部变量，不会产生线程同步问题 所以没必要用stringbuffer

2017-04-27 23:22 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/dao/abstracts/IHistoryRecordGate.java
> +        hour, day, month;
一般枚举型的值是全部大写，一个惯例

2017-04-28 14:35 UTC, HYKINGDOM reviewed
--修改业务层代码
--优化代码

2017-04-28 14:35 UTC, HYKINGDOM commented on Web/ExpressIM/src/com/stardust/express/dao/abstracts/IHistoryRecordGate.java
> +        hour, day, month;
枚举型的大小写不用和前端大小写对应么

2017-04-28 14:35 UTC, HYKINGDOM commented on Web/ExpressIM/src/com/stardust/express/actions/ChartAction.java
> +        bo.getPeriodSummaryMap(startDate,endDate,summaryType);
ChartAction  是昨晚写来测试连接的   发现startDate和endDate  取不到前端的值  sql打印语句 startDate和endDate哪里是null

2017-04-28 14:35 UTC, HYKINGDOM commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +        for (int i = 0; i <= summarylist.size(); i++) {
foreach 昨晚没写出来  然后我就把 原来for循环修改了一下  idealdebug 模式 用得不太熟练 一会上班 我再研究一下

2017-04-29 02:36 UTC, codedoggylicheng approved these changes

2017-04-29 02:36 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +        String key = "";
这个key还有必要吗

2017-04-29 02:36 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/bo/HistoryRecordBO.java
> +        String key = "";
这个key还有必要吗？

2017-04-29 02:36 UTC, codedoggylicheng commented on Web/ExpressIM/src/struts.xml
> +        <action name="ChartAction" class="com.stardust.express.actions.ChartAction" method="chartSummryProidBy">
这个action的名字太通用了，之后新的图表进来不太好命名。不过可以做下个图表的时候再改

2017-04-29 02:36 UTC, codedoggylicheng commented on Web/ExpressIM/src/com/stardust/express/dao/implementations/HistoryRecordGate.java
> +            //query.setParameter(0,startDate);
去掉注释行

2017-04-29 02:57 UTC, codedoggylicheng commented
@HYKINGDOM @planr0423 
这条和这个PR没有直接关系，但是之后的PR需要注意.每个commit的注释都需要有明确的意义。如下例:
<img width="1090" alt="screen shot 2017-04-29 at 10 53 17 am" src="https://cloud.githubusercontent.com/assets/27494407/25552370/3f27dcd2-2cca-11e7-86c5-bf86cd038b9c.png">

每一个commit其他人都可以看到这个commit是干嘛的。其他人可以单独的看一个commit的内容，现在这个PR的commit的描述，有hu, huyi,hy。这种毫无意义的注释过于混乱。

如果想在技术上有成长要稳扎稳打，认真对待每一行代码每一个pr每一个commit

2017-04-29 03:30 UTC, codedoggylicheng commented
LGTM 👍

2017-04-29 03:38 UTC, merged